### ISSUE TITLE
Practica7_Costos_y_Juicio_Experto

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-m#1]
[Practica7_Unidad3_Gestion_de_proyectos.pdf](https://github.com/user-attachments/files/17497898/Practica7_Unidad3_Gestion_de_proyectos.pdf)

**Comment by carlos0716c** [comment]
Cumple con buena portada y los escudos institucionales: 25 puntos
Describe el procedimiento: 25 puntos
Incluye ilustraciones y capturas: 25 puntos
Conclusion: 25 puntos
Puntaje alcanzado 100% = 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
